### ISSUE TITLE
Edges from nodes not in the vertex list reappear unexpectedly

### ISSUE THREAD

**Issue by manleyjster** [haskell/fgl#13]
Hi -

I've noticed that fgl behaves in unexpected ways for edges from vertices not in the vertex list.

For example, at the repl:

```haskell
> import Data.Graph.Inductive.Graph as Graph
> import Data.Graph.Inductive.PatriciaTree (Gr)
> let g = Graph.mkGraph [(1,())] [(1,2,True), (2,1,False)] :: Gr () Bool
> g 
mkGraph [(1,()] [(1,2,True)] -- The edge (2,1,False) has disappeared.
> let g' = Graph.insNode [(2,())] g
> g'
mkGraph [(1,()), (2,())] [(1,2,True)] -- Just as we expect, the edge (2,1,False) is absent.
> Graph.delEdge (1,2) g'
mkGraph [(1,()), (2,())] [(2,1,False)] -- What!?!?! The edge (2,1,False) mysteriously reappeared!
```

Having mkGraph ignore edges from vertices not in the vertex list is fine. However, once those edges have been thrown away, they shouldn't come back unexpectedly.

**Comment by manleyjster** [comment]
Thanks to [nick8325](https://github.com/nick8325/) for helping me understand this behavior in https://github.com/nick8325/quickcheck/issues/53!

**Comment by manleyjster** [comment]
By the way - I'm using fgl 5.5.1.0.

**Comment by ivan-m** [comment]
Hmmmm.... this is a bug in that:

> let g = Graph.mkGraph [(1,())] [(1,2,True), (2,1,False)] :: Gr () Bool

Should return an error: you're referencing nodes that don't exist in the graph!

(And that's what I get when I try this:

```
mkGraph *** Exception: Data/Graph/Inductive/Graph.hs:229:5-38: Irrefutable pattern failed for pattern (Data.Maybe.Just (pr,
                                                         _,
                                                         la,
                                                         su),
                                        g')
```
but that might be from changes I've made since the release.)

This occurs, as there is no validation that occurs in `mkGraph`; there are two possible ways of handling this:
* Add validation to `mkGraph`; this will make it slower and less efficient for the (more common I think) cases of correct usage
* Keep doing what it does (in HEAD) of throwing an error

Unless there's a compelling reason, I don't think I'll change the behaviour.

To be able to use QuickCheck with FGL, see #12.

**Comment by manleyjster** [comment]
Ah, I see. Good to know that the behavior has been fixed in master. Thanks!
