### ISSUE TITLE
Add monadic graphs in the ST monad

### ISSUE THREAD

**Issue by ppetr** [haskell/fgl#25]
I just discovered that there is a class for monadic graphs, but there is only an `IO` based representation. I propose to add a more general implementation based on [`MArray`](https://hackage.haskell.org/package/array-0.5.1.0/docs/Data-Array-MArray.html#t:MArray) that'd allow both `IO` and `ST` based representations. In particular the `ST` version would allow high performance while keeping results pure.

If this make sense, I'll be happy to eventually contribute this.

**Comment by ivan-m** [comment]
Pull requests accepted :)

I admittedly haven't touched the monadic graph parts much, as I haven't had a need to.

One alternative I was thinking of (though this would be in a separate package due to the additional dependency) is to provide an MVector-backed implementation, as it would probably be more performant than using MArray.

**Comment by ivan-m** [comment]
Are you still able and willing to submit a pull request for this?

**Comment by ppetr** [comment]
Yes, I'd like to contribute this, it just slipped my attention. I'll try to
work on it in upcoming weeks.

**Comment by ivan-m** [comment]
No worries.
