### ISSUE TITLE
Eq instance of LPath seems incorrect

### ISSUE THREAD

**Issue by jhrcek** [haskell/fgl#59]
The implementation of `Eq` of `LPath` is only looking at the first label in non-empty path [here](https://github.com/haskell/fgl/blob/master/Data/Graph/Inductive/Graph.hs#L100). This leads to incorrect results when comparing paths longer than 1, e.g.
```
GHCI> LP [(1,'a'),(2,'b')] == LP [(1,'a'),(2,'c')]
True
```
I believe the non-empty path case should be changed to something like:
`(LP ((_,x):xs)) == (LP ((_,y):ys)) = x==y && LP xs == LP ys`

There's similar problem with `Ord` instance. [](url)

**Comment by ivan-m** [comment]
I believe this is deliberate due to how `LPath` values are constructed and examined, hence the third case.

Have you had an actual problem with this instance definition?

(Note that if this were an actual problem then the definition would be even easier: `(==) `on` map fst . unLPath`.)

**Comment by ivan-m** [comment]
Actually, these instances aren't ever used :man_facepalming: 

I'm guessing it used to be used by `Data.Graph.Inductive.Internal.RootPath` (as that's where the instance used to live), but it's been that way since I first imported fgl into git.

Unless an actual use-case breaks because of these instance definitions, I'm going to leave them as-is in case someone is relying upon their behaviour (as it isn't something that can be picked up statically).

**Comment by ivan-m** [comment]
Just checked: the earliest version of fgl on Hackage is 5.3, and the instances don't seem to be used there either. _shrug_

**Comment by jhrcek** [comment]
Ok, no specific use case of mine was broken by the existing definition.
